stty -ixon

export PS1="\[$(tput bold)\]\[$(tput setaf 1)\][\[$(tput setaf 3)\]\u\[$(tput setaf 2)\]@\[$(tput setaf 4)\]\h \[$(tput setaf 5)\]\W\[$(tput setaf 1)\]]\[$(tput setaf 7)\]\\$ \[$(tput sgr0)\]"

if [[ -f /usr/bin/waterfox ]]; then
	export BROWSER="waterfox"
elif [[ -f /usr/bin/palemoon ]]; then
	export BROWSER="palemoon"
elif [[ -f /usr/bin/iceweasel ]]; then
	export BROWSER="iceweasel"
else
	export BROWSER="firefox"
fi

export EDITOR="vim"
export PATH=$PATH:$HOME/.config/Scripts

shopt -s autocd

#if [[ -z $DISPLAY ]] && [[ $(tty) = /dev/tty1 ]]; then
	#exec startx
#fi

#Basic Aliases
alias v="vim"
alias r="ranger"
alias ls='ls -hN --color=auto --group-directories-first'
#alias ls='ls++'
alias lsa='ls -A'
g() { cd $1 && ls -a ;}
alias mkdir="mkdir -pv"
alias e="exit"
alias crep="grep --color=always"

alias sv="sudo vim"

alias p="sudo pacman"

alias sdn="sudo shutdown now"

alias yt="youtube-dl -ic"
alias yta="youtube-dl -xic"

aurinstall() { curl -O https://aur.archlinux.org/cgit/aur.git/snapshot/$1.tar.gz && tar -xvf $1.tar.gz && cd $1 && makepkg --noconfirm -si && cd .. && rm -rf $1 $1.tar.gz ;}

alias ein="ssh -l einchan -p 22 104.238.215.7"
alias starwars="telnet towel.blinkenlights.nl"

alias temp="cp ~/Repos/website/template.php"

alias nf="clear && neofetch"
alias clock="ncmpcpp -s clock"
alias rss="vim ~/Repos/website/rss.xml"

alias newnet="sudo systemctl restart NetworkManager"
alias atltime="sudo timedatectl set-timezone America/New_York && i3 restart"
alias tuctime="sudo timedatectl set-timezone America/Phoenix && i3 restart"

bl() { convert $@ -resize 1440x1080\> bl_$@ ;}

alias pingme="ping lukesmith.xyz"

alias youtube="youtube-viewer"
alias YT="youtube-viewer"
alias syt="youtube-viewer"

alias Txa="cp ~/Documents/LaTeX/article.tex"
alias Txs="cp ~/Documents/LaTeX/beamer.tex"
alias Txh="cp ~/Documents/LaTeX/handout.tex"
alias TC='texclear'

getgit() { git clone http://github.com/$1.git ;}

weath() { curl wttr.in/$1 ;}
alias work="mkdir ~/Work && cd ~/Work"


CF() { cd ~/.config/$1 && ls ;}

alias ethspeed="speedometer -r enp0s25"

alias notes="vim ~/notes"

alias mailsync="bash ~/.config/Scripts/mailsyncloop"

alias wifispeed="speedometer -r wlp2s0"

alias tr="transmission-remote"

alias ref="python ~/.config/Scripts/shortcuts.py && source ~/.bashrc"

alias ka="killall"

alias bars="bash ~/.config/polybar/launch.sh"

alias lsc="screen.sh l"
alias vsc="screen.sh v"
alias dsc="screen.sh d"

alias speedvid="bash ~/.config/Scripts/speedvid.sh"

alias g="git"
alias gitup="git push origin master"
alias gitall="git add . && git commit -m "whatever" && git push origin master"

#Directory Shortcuts:
