"""Collection of all exceptions raised by this tool"""

class BaseError(Exception):
    """Base class for all exceptions generated by this tool"""
    pass

class ModuleLoadError(BaseError):
    """Raised whenever loading a module fails"""
    pass

class ThemeLoadError(BaseError):
    """Raised whenever loading a theme fails"""
    pass

# vim: tabstop=8 expandtab shiftwidth=4 softtabstop=4
