#!/bin/sh
while read -r file
do
	case "$1" in
		"w" )
			setbg "$file" & ;;
		"c" )
			[ -z "$destdir" ] && destdir="$(eval \
				echo "$(awk '{ sub(/#.*/, ""); if (NF) print $2 }' "${XDG_CONFIG_HOME:-$HOME/.config}/shell/bm-dirs" |
				dmenu -l 20 -i -p "Copy file(s) to where?")")"
			[ ! -d "$destdir" ] && notify-send "$destdir is not a directory, cancelled." && exit
			cp "$file" "$destdir" && notify-send -i "$(readlink -f "$file")" "$file copied to $destdir." & ;;
		"m" )
			[ -z "$destdir" ] && destdir="$(eval \
				echo "$(awk '{ sub(/#.*/, ""); if (NF) print $2 }' "${XDG_CONFIG_HOME:-$HOME/.config}/shell/bm-dirs" |
				dmenu -l 20 -i -p "Move file(s) to where?")")"
			[ ! -d "$destdir" ] && notify-send "$destdir is not a directory, cancelled." && exit
			mv "$file" "$destdir" && notify-send -i "$(readlink -f "$file")" "$file moved to $destdir." & ;;
		"r" )
			magick "$file" -rotate 90 "$file" ;;
		"R" )
			magick "$file" -rotate -90 "$file" ;;
		"f" )
			magick "$file" -flop "$file" ;;
		"y" )
			printf %s "${file##*/}" | xclip -selection clipboard &&
			notify-send "$file copied to clipboard" & ;;
		"Y" )
			readlink -f "$file" | tr -d "\n" | xclip -selection clipboard &&
			notify-send "$(readlink -f "$file") copied to clipboard" & ;;
		"x" )
			xclip -selection clipboard -target image/png "$file" && notify-send "Image copied to clipboard" & ;;
		"d" )
			[ "$(printf "No\nYes" | dmenu -i -p "Really delete $file?")" = "Yes" ] &&
			rm "$file" && notify-send "$file deleted." ;;
		"g" )
			ifinstalled gimp && setsid -f gimp "$file" ;;
		"i" )
			notify-send "File information" "$(mediainfo "$file" | sed "s/[ ]\+:/:/g;s/: /: <b>/;s/$/<\/b>/" | grep "<b>")" ;;
	esac
done
