#!/bin/sh
# Podboat sucks. This script replaces it.
# It reads the newsboat queue, queuing downloads with taskspooler.
# It also removes the junk from extentions.
queuefile="$HOME/.local/share/newsboat/queue"

while read -r line; do
	[ -z "$line" ] && continue
	url="$(echo "$line" | awk '{print $1}')"
	base="$(basename "$url")"
	notify-send -i "$PIX/dl.png" "Queuing $base..."
	idnum="$(tsp curl -LO "$url")"
	realname="$(echo "$base" | sed "s/?\(source\|dest\).*//;s/%20/ /g")"
	tsp -D "$idnum" mv "$base" "$realname"
	tsp -D "$idnum" notify-send -i "$PIX/check.png" "$realname done."
done < "$queuefile"

echo > "$queuefile"
