#!/bin/sh
# This script is called by i3 on startup to remap keys.
# Increase key speed via a rate change
xset r rate 300 50

# Clear the options
setxkbmap -option
# set my the preferd keymap
setxkbmap se us
# Map the caps lock key to super...
setxkbmap -option caps:super
# But when it is pressed only once, treat it as escape.
killall xcape 2>/dev/null ; xcape -e 'Super_L=Escape'
# Map the menu button to right super as well.
xmodmap -e 'keycode 135 = Super_R'

# Make scroll natural on parvus
if xinput --list-props "Elan Touchpad" > /dev/null ; then
xinput set-prop 'Elan Touchpad' 'libinput Natural Scrolling Enabled' 1
fi



