#!/bin/sh
# Sets the background. If given an argument, will set file as background.
[ ! -z "$1" ] && cp "$1" ~/.config/wall.jpg && notify-send -i "$HOME/.config/wall.jpg" "Wallpaper changed."
xwallpaper --zoom ~/.config/wall.jpg
