#!/bin/sh
# Sets the background. Many scripts need to do this, but I've put it here so you can easily change all their actions.
#setroot -z ~/.config/wall.png # with setroot
feh --bg-scale "$HOME/.config/wall.png" # feh
