#!/bin/sh
# Syncs repositories and downloads updates, meant to be run as a cronjob.

ping -q -w 1 -c 1 `ip r | grep -m 1 default | cut -d ' ' -f 3` >/dev/null || exit

notify-send -i "$PIX/larbs.svg" "Checking for pacakge updates..."

sudo pacman -Syyuw --noconfirm || notify-send "Error downloading updates.

Check your internet connection, if pacman is already running, or run update manually to see errors."
pkill -RTMIN+8 i3blocks

if pacman -Qu | grep -v "\[ignored\]"
then
	notify-send -i "$PIX/larbs.gif" "Package updates available. Click statusbar icon (📦) for update."
else
	notify-send -i "$PIX/larbs.gif" "Repository sync complete. No new packages for update."
fi
