#!/bin/sh
# Syncs repositories and downloads updates, meant to be run as a cronjob.

ping -q -w 1 -c 1 `ip r | grep -m 1 default | cut -d ' ' -f 3` >/dev/null || exit

note "Checking for pacakge updates..." "$PIX/larbs.gif"

sudo pacman -Syyuw --noconfirm || note "Error downloading updates.

Check your internet connection, if pacman is already running, or run update manually to see errors."
pkill -RTMIN+8 i3blocks

if pacman -Qul
then
	note "Package updates available. Click statusbar icon for update." "$PIX/larbs.gif"
else
	note "Repository sync complete. No new packages for update." "$PIX/larbs.gif"
fi
