#!/bin/sh
# Toggles all cronjobs off/on.
# Stores disabled crontabs in ~/.consaved until restored.

([ -f ~/.cronsaved ] && crontab - < ~/.cronsaved  && rm ~/.cronsaved && notify-send "🕓 Cronjobs re-enabled.") || ( crontab -l > ~/.cronsaved && crontab -r && notify-send "🕓 Cronjobs saved and disabled.")
