#!/bin/sh

case $BLOCK_BUTTON in
	1) notify-send "🖥 CPU hogs" "$(ps axch -o cmd:15,%cpu | awk '{ arr[$1] += $2 }; END { for (i in arr) { print i,arr[i] } }' | sort -nrk2 | head -n10)" ;;
	3) notify-send "🖥 CPU module " "\- Shows CPU temperature.
- Click to show intensive processes.
- % is of single core." ;;
esac

sensors | awk '/Core 0/ {print $3}'
