#!/bin/sh

# i3blocks newsboat module.
# Displays number of unread news items and an loading icon if updating.
# When clicked, brings up `newsboat`.

case $BLOCK_BUTTON in
        1) "$TERMINAL" -e newsboat ;;
        3) pgrep -x dunst >/dev/null && notify-send "<b>📰 News module:</b>
- Shows unread news items
- Left click opens newsboat" ;;
esac

echo " $(newsboat -x print-unread | awk '{ print $1}' | sed s/^0$//g)$(cat ~/.config/newsboat/.update 2>/dev/null)"
