#!/bin/sh

# This script records audio.
# It runs an appropriate record script for either ALSA and Pulseaudio.
# It also names files smartly to prevent overwrites.

# Picks a file name for the output file based on availability:
while [ -f "$HOME/audio$n.flac" ]
do
	n=$((n+1))
done
filename="$HOME/audio$n.flac"

ffmpeg \
-f alsa -i default \
-c:a flac \
"$filename" &

# PID outputted for use by the killrecording script
echo $! > ~/.recordingpid
# Updating i3blocks recording icon:
echo 🎙️ > ~/.recordingicon && pkill -RTMIN+9 i3blocks
