#!/bin/bash

# This script will compile or run another finishing operation on a document. I
# have this script run via vim.
#
# tex files: Compiles to pdf, including bibliography if necessary
# md files: Compiles to pdf via pandoc
# rmd files: Compiles via R Markdown
# config.h files: (For suckless utils) recompiles and installs program.
# all others: run `sent` to show a presentation

oridir=$(pwd)

file=$(readlink -f "$1")
dir=$(dirname "$file")
base="${file%.*}"
cd $dir

textype() { \
	command="pdflatex"
	( sed 5q "$file" | grep -i -q 'xelatex' ) && command="xelatex"
	$command --output-directory="$dir" "$base" &&
	grep -i addbibresource "$file" &&
	biber --input-directory "$dir" "$base" &&
	$command --output-directory="$dir" "$base" &&
	$command --output-directory="$dir" "$base"
	}

case "$file" in
	*\.rmd) echo "require(rmarkdown); render('$file')" | R --vanilla ;;
	*\.tex) textype "$file" ;;
	*\.md) pandoc "$file" --pdf-engine=xelatex -o "$base".pdf ;;
	*config.h) make && sudo make install ;;
	*) sent "$file" 2>/dev/null & ;;
esac
cd $oridir
