#!/bin/sh
# Notify me with notify-send if my battery is below 25%.
# You can set this to run via cron.

[ "$(cat /sys/class/power_supply/BAT0/status)" = "Charging" ] && exit
[ "$(cat /sys/class/power_supply/BAT0/capacity)" -lt 25 ] &&
export DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1001/bus &&
notify-send -u critical "Battery critically low."
