#!/bin/sh

elsewhere() { echo Key mappings available for the following programs:
ls ~/.larbs
echo Run \`getkeys\` followed by a program name to get bindings ;}

if [[ -f ~/.scripts/.getkeys/$1 ]]; then
cat ~/.scripts/.getkeys/$1
else
echo Run command with one of the following arguments for info about that program:
ls ~/.scripts/.getkeys
fi
