#!/bin/bash
case $BLOCK_BUTTON in
    1) $TERMINAL -e sudo pacman -Syu && pacman -Qu | wc -l > ~/.larbs/.pacupgrade && pkill -RTMIN+8 i3blocks ;;
esac

pacman -Qu | wc -l | sed -e '/^0$/d' > ~/.larbs/.pacupgrade && pkill -RTMIN+8 i3blocks

cat ~/.larbs/.pacupgrade | sed -e "/^$/d"
