#!/bin/bash

# A general audio interface for LARBS.

newvol="pkill -RTMIN+10 i3blocks"
# Uncomment if i3mpdupdate isn't running:

case "$1" in
	"up") pulsemixer --change-volume +"$2" ; $newvol ;;
	"down") pulsemixer --change-volume -"$2" ; $newvol ;;
	"mute") pulsemixer --toggle-mute ; $newvol ;;
	"truemute") pulsemixer --mute ; $newvol ;;
	"toggle") mpc toggle ;;
	"pause") mpc pause ; pauseallmpv ;;
	"forward") mpc seek +"$2" ;;
	"back") mpc seek -"$2" ;;
	"next") mpc next ;;
	"prev") mpc prev ;;
	"replay") mpc seek 0% ;;
esac
