#!/bin/bash

# Map the caps lock key to super...
setxkbmap -layout us -variant altgr-intl -option caps:super
# But when it is pressed only once, treat it as escape.
xcape -e 'Super_L=Escape'

# Map the menu button to right super as well.
xmodmap -e 'keycode 135 = Super_R'
#keycode 135 = Super_R NoSymbol Super_R
