#!/bin/bash

# This script records video.
# It also names files smartly to prevent overwrites.

# Picks a file name for the output file based on availability:
while [[ -f $HOME/video$n.mkv ]]
do
	n=$((n+1))
done
filename="$HOME/video$n.mkv"

# The actual ffmpeg command:
ffmpeg \
-f x11grab \
-s $(xdpyinfo | grep dimensions | awk '{print $2;}') \
-i :0.0 \
 -c:v libx264 -qp 0 -r 30 $filename &

# Updating i3blocks recording icon:
echo ⏺️ > ~/.scripts/.recording && pkill -RTMIN+9 i3blocks
