#!/bin/sh

# Toggle floating dropdown terminal in i3, or start if non-existing.
# $1 is	the script run in the terminal.
# All other args are terminal settings.
# Terminal names are in dropdown_* to allow easily setting i3 settings.

[ -z "$1" ] && exit

if xwininfo -tree -root | grep "(\"dropdown_$1\" ";
then
	echo "Window detected."
	i3 "[instance=\"dropdown_$1\"] scratchpad show; [instance=\"dropdown_$1\"] move position center"
else
	echo "Window not detected... spawning."
	i3 "exec --no-startup-id $TERMINAL -n dropdown_$1 $(echo "$@" | cut -d ' ' -f2-) -e $1"
fi
