#!/bin/sh
# Pause mpd and send the pause key to all mpv videos:
mpc pause >/dev/null 2>&1
pauseallmpv >/dev/null 2>&1



# If `imagemagick` is not installed, use a colored screen.
[ -f /usr/bin/convert ] &&
	rm -f /tmp/locked.png && # remove old lock img
	scrot -m -z /tmp/base.png && # Take a screen shot
	pgrep -x dunst && notify-send -i ~/.scripts/pix/lock.png "Locking computer..." &&
	convert /tmp/base.png -blur 0x8 /tmp/locked.png &&
	i3lock -e -f -c 000000 -i /tmp/locked.png

i3lock -e -f -c 1d2021

# In five seconds, turn off display unless key press in last 4 seconds.
sleep 5 && [ 4000 -lt "$(xssstate -i)" ] &&  pgrep -x i3lock && xset dpms force off
