#!/bin/sh
vidlist="
status bar	https://www.youtube.com/watch?v=gKumet6b-WY
sxiv (image viewer)	https://www.youtube.com/watch?v=GYW9i_u5PYs
st (terminal)	https://www.youtube.com/watch?v=9H75enWM22k
i3 (window manager)		https://www.youtube.com/watch?v=GKviflL9XeI
pacman (installing/managing programs)	https://www.youtube.com/watch?v=-dEuXTMzRKs
mutt (email)		https://www.youtube.com/watch?v=2U3vRbF7v5A
ncmpcpp (music player)		https://www.youtube.com/watch?v=sZIEdI9TS2U
newsboat (RSS reader)	https://www.youtube.com/watch?v=dUFCRqs822w
zathura (pdf viewer)		https://www.youtube.com/watch?v=V_Iz4zdyRM4
gpg keys	https://www.youtube.com/watch?v=DMGIlj7u7Eo
calcurse (calendar)	https://www.youtube.com/watch?v=hvc-pHjbhdE
urlview		https://www.youtube.com/watch?v=IgzpAjFgbCw
colorschemes with pywal	https://www.youtube.com/watch?v=Es79N_9BblE
vi mode in shell	https://www.youtube.com/watch?v=GqoJQft5R2E
"
echo "$vidlist" | grep -P "^$(echo "$vidlist" | grep "https:" | sed 's/\t.*//g' | dmenu -i -p "Learn about what? (ESC to cancel)" -l 20 | awk '{print $1}')\s" | sed 's/.*\t//' | xargs -r mpv
