#!/bin/sh
vidlist="
status bar	https://www.youtube.com/watch?v=gKumet6b-WY
feh
i3
mutt		https://www.youtube.com/watch?v=2U3vRbF7v5A
ncmpcpp		https://www.youtube.com/watch?v=sZIEdI9TS2U
newsboat	https://www.youtube.com/watch?v=dUFCRqs822w
ranger		https://www.youtube.com/watch?v=L6Vu7WPkoJo
zathura		https://www.youtube.com/watch?v=V_Iz4zdyRM4
gpg keys	https://www.youtube.com/watch?v=DMGIlj7u7Eo
calcurse	https://www.youtube.com/watch?v=hvc-pHjbhdE
urlview		https://www.youtube.com/watch?v=IgzpAjFgbCw
colorschemes with pywal	https://www.youtube.com/watch?v=Es79N_9BblE
vi mode in shell	https://www.youtube.com/watch?v=GqoJQft5R2E
"

mpv "$(echo "$vidlist" | grep -P "^$(echo "$vidlist" | grep "https:" | sed 's/\t.*//g' | dmenu -i -p "Learn about what? (ESC to cancel)" -l 5)\\t" | sed 's/.*\t//')"
