#!/bin/sh
# Credit to Maddison Hellstrom (@b0o on Github)
ifinstalled feh && qrencode -o - -s 1 \
	"$(xclip -out -selection clipboard)" |
	feh --zoom max \
		-F \
		--force-aliasing \
		--image-bg white \
		-
